### ISSUE TITLE
Make the mouse stay in the center and disappear

### ISSUE THREAD

**Issue by pawsplay** [SMoscon/RuGBY#20]
This is so you can click without the risk of clicking outside of the window.

**Comment by pcyang** [comment]
Screen.showCursor = false;
This will hide the cursor. Locking the cursor will cancel the movement of the FPS viewing. This should be sufficient since window mode is intended to allow player to click outside of the window.
I will close this issues once I get a up-to-date copy of the working code. I am thinking about in NetworkManager, OnServerInitalized, after SpawnPlayer();

**Comment by pawsplay** [comment]
I would like to play the game in Fullscreen, or windowed, and have the mouse lock to the center so that people can't click out of the window. The game is fast paced and competitive, so clicking out of the window would be extremely detrimental to the experience.

However, we should have a toggle button for the visibility and mobility of the mouse. Eventually, when the mouse is out, we should also disable the camera movement, but that's not necessary right now.

**Comment by pcyang** [comment]
Okay @pawsplay so having
Screen.lockCursor = true;
will hide and keep the mouse in the screen. It is now impossible to click outside of the window, or stop the game engine... the only way is ESC. Sounds good?
